name: student_monitoring
description: Student Monitoring Application
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # state management
  stacked: ^1.7.6

  # navigation
  auto_route: 
  stacked_services: ^0.6.0+1

  # inversion of control
  get_it:
  injectable:

  # svg
  flutter_svg:

  # email validator
  email_validator: ^1.0.6

  # firebase related
  firebase_auth: ^0.14.0+5
  firebase_dynamic_links: ^0.5.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner:
  auto_route_generator:
  injectable_generator:

flutter:
  uses-material-design: true

  assets:
    - lib/assets/image/

  fonts:
    - family: OpenSans
      fonts:
      - asset: lib/assets/font/OpenSans-Regular.ttf
        style: normal
      - asset: lib/assets/font/OpenSans-SemiBold.ttf
        weight: 600