name: student_monitoring
description: Student Monitoring Application
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # state management
  stacked: ^1.7.6

  # navigation
  auto_route: 
  stacked_services: ^0.6.0+1

  # inversion of control
  get_it:
  injectable:

  # svg
  flutter_svg:

  # email validator
  email_validator: ^1.0.6

  # firebase related
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_dynamic_links: ^0.5.1
  cloud_firestore: ^0.14.4

  # battery
  battery: ^1.0.7

  # internet
  internet_speed_test: ^1.1.2+1
  
  # flutter isolate
  flutter_isolate: ^1.0.0+14

  # spinkit for loading animation
  flutter_spinkit: "^4.1.2"

  # signal strength
  signal_strength_indicator: ^0.3.1

  # battery indicator
  battery_indicator: ^0.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner:
  auto_route_generator:
  injectable_generator:

flutter:
  uses-material-design: true

  assets:
    - lib/assets/image/

  fonts:
    - family: OpenSans
      fonts:
      - asset: lib/assets/font/OpenSans-Regular.ttf
        style: normal
      - asset: lib/assets/font/OpenSans-SemiBold.ttf
        weight: 600